services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env.local
    volumes:
      - ./web:/app
      - ./.docker-cache/next:/app/.next/cache
    command: sh -c "bun install && bun run dev"
    depends_on:
      - gate

  gate:
    build:
      context: ./gate
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./gate/.env.local
    volumes:
      - ./gate:/app
    command: sh -c "bun install && bun run dev"
    depends_on:
      - gate
